### ISSUE TITLE
Rider update for the Wiki

### ISSUE THREAD

**Issue by Drew-Chase** [malforge/mdk2#28]
I wrote up a quick wiki page for Rider usage.
Here is a zip with all the images and markdown file: [mdk2-wiki-rider-update.zip](https://github.com/user-attachments/files/16325539/mdk2-wiki-rider-update.zip)

# Getting Started using JetBrain's Rider
## With terminal
Open your terminal of choice, I'll be using [Windows Terminal](ms-windows-store://pdp?hl=en-us&gl=us&referrer=storeforweb&source=https%3A%2F%2Fwww.google.com%2F&productid=9n0dx20hk701&ocid=storeweb-pdp-open-cta) and [Powershell](ms-windows-store://pdp?hl=en-us&gl=us&referrer=storeforweb&source=https%3A%2F%2Fwww.google.com%2F&productid=9mz1snwt0n5d&ocid=storeweb-pdp-open-cta)
![dotnet-install](https://github.com/user-attachments/assets/ee7999ec-4ebe-455c-b246-3f04f9f26926)    
Once completed, you should get this message.   
![dotnet-install-done](https://github.com/user-attachments/assets/c387aa44-821f-4940-89d8-118d6c74bce6)   
Open JetBrain's Rider
Click the new Solution button.   
![new-solution](https://github.com/user-attachments/assets/01605907-0310-4621-8314-e4084f96fd10)
Now you should have two templates added, Programmable Block Script (MDK2) and Programmable Block Mixin (MDK2)   
![templates](https://github.com/user-attachments/assets/5c708cd6-12fc-4850-b8e5-2f52469b392b)

## With JetBrains Interface
1. Download the nuget package [Mal.Mdk2.ScriptTemplates](https://www.nuget.org/packages/Mal.Mdk2.ScriptTemplates)   
![download-nuget-package](download-nuget-package.png)
2. Open JetBrain's Rider
3. Click the new Solution button.   
![new-solution](https://github.com/user-attachments/assets/01605907-0310-4621-8314-e4084f96fd10)
4. Click "Manage Templates..." button.   
![manage-templates](https://github.com/user-attachments/assets/58f732dd-e6f1-4e11-98da-4a426adbd875)
5. Click "Install Template..."   
![install template](install-template.png)
6. Navigate to where you downloaded the nuget package, select it and click open.
![select-nuget](https://github.com/user-attachments/assets/335453b4-2f47-45c2-8af4-2ea93e574bb5)
7. Click "close"   
![close](https://github.com/user-attachments/assets/6d7cd32e-aa7e-4e83-89e5-43a5aa80e091)
Now you should have two templates added, Programmable Block Script (MDK2) and Programmable Block Mixin (MDK2)   
![templates](https://github.com/user-attachments/assets/5c708cd6-12fc-4850-b8e5-2f52469b392b)

**Comment by malware-dev** [comment]
Hah, fantastic, I hadn't gotten around to this yet. Thanks a lot!
