### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by ultimateshadsform** [malforge/mdk2#35]
![image](https://github.com/user-attachments/assets/c5b748cd-68cb-4195-a8e8-03f032ef50ac)

I really don't know what to do.

**Comment by ultimateshadsform** [comment]
nvm. for some reason the nuget original source was missing so I just added it.

**Comment by malware-dev** [comment]
Yes, surprisingly this seem to be a thing for some people.

I should probably add this to the instructions.

Thank you.

**Comment by ultimateshadsform** [comment]
Could also add that you can open the solution explorer in vscode and right click the project and press "build" and it will create the ingame script.
