### ISSUE TITLE
Minifier error message points to different file and symbol.

### ISSUE THREAD

**Issue by irreality-net** [malforge/mdk2#37]
The error message:
```
1>Verifying that nothing went wrong
1>C:\Projects\___\obj\intermediate-script.cs(132,51): error CS0115: 'O.u()': no suitable method found to override
1>Failed to compile the project.
```
Double clicking the error opens C:\Projects\__\obj\intermediate-script.cs at line 132 but failing code is in C:\Projects\___\obj\intermediate-script.WhitespaceTrimmer.cs

Additionally method name is 'ų' not 'u', but once known how to identify the correct file name it is easy to spot:
public override string ų() {}

**Comment by malware-dev** [comment]
Not a bug. 

1. intermediate-script.cs is the only one that gets compiled. The WhitespaceTrimmer.cs file is just another intermediate before we come to this level.
2. I can't control how the compiler shows its errors. That's a standard C# compiler error message.
