### ISSUE TITLE
Correction for Getting Started using Visual Studio Guide - Adding NuGet as a source

### ISSUE THREAD

**Issue by dylanvignola** [malforge/mdk2#39]
I may be the silly one here, but using the latest version of Visual Studio 17.11.3 the command provided in the Getting Started with Visual Studio Guide to add NuGet 'dotnet nuget add source --name "NuGet.org" --source "https://api.nuget.org/v3/index.json"' throws a syntax error

After some googling the command that did work is "dotnet nuget add source https://api.nuget.org/v3/index.json -n NuGet.org"

Just thought I would offer this as a possible (?) correction, if any others have this issue!

**Comment by malware-dev** [comment]
Yep, I don't know why that's wrong...

**Comment by malware-dev** [comment]
Question remains why the heck you need to do this in the _first_ place, but, you know... it is what it is.
