### ISSUE TITLE
Cannot import System.Collections.Immutable for Scripts with IGC

### ISSUE THREAD

**Issue by MistaLemur** [malforge/mdk2#43]
I am getting the following error when I run `dotnet build`
```
error MDK01: The type or member 'ImmutableArray<MyTuple<long, long, Vector3D, Vector3D, double>>' is prohibited in Space Engineers 
```
This occurs with any types from System.Collections.Immutable

IDE is VS Code

**Comment by malware-dev** [comment]
Are you sure your nuget packages are up to date?

**Comment by MistaLemur** [comment]
```
The following template packages will be installed:
   Mal.Mdk2.ScriptTemplates

Mal.Mdk2.ScriptTemplates (version 2.0.5) is already installed, it will be replaced with latest version.
Mal.Mdk2.ScriptTemplates::2.0.5 was successfully uninstalled.
Success: Mal.Mdk2.ScriptTemplates::2.0.5 installed the following templates:
Template Name                     Short Name    Language  Tags
--------------------------------  ------------  --------  --------------------
Programmable Block Mixin (MDK2)   mdk2pbmixin   [C#]      MDK: Space Engineers
Programmable Block Script (MDK2)  mdk2pbscript  [C#]      MDK: Space Engineers
```

**Comment by MistaLemur** [comment]
I am also seeing this issue when I open the project in Visual Studio 22 v17.11.4
![image](https://github.com/user-attachments/assets/e25376f8-03c3-46f4-a6c8-cef017a5649e)

**Comment by malware-dev** [comment]
I was asking about the _nuget packages_ not the templates?

**Comment by malware-dev** [comment]
I'm not in a position where I can test myself right now

**Comment by MistaLemur** [comment]
`dotnet list package` gives...
```
   [net48]: 
   Top-level Package           Requested   Resolved
   > Mal.Mdk2.PbAnalyzers      2.1.9       2.1.9   
   > Mal.Mdk2.PbPackager       2.0.6       2.0.6   
   > Mal.Mdk2.References       2.2.2       2.2.2   
```

**Comment by MistaLemur** [comment]
I have updated my mdk packages to 
```
   Top-level Package           Requested   Resolved
   > Mal.Mdk2.PbAnalyzers      2.1.9       2.1.9
   > Mal.Mdk2.PbPackager       2.0.9       2.0.9
   > Mal.Mdk2.References       2.2.3       2.2.3
   ```
   
 I am still seeing this issue unfortunately.

**Comment by malware-dev** [comment]
![image](https://github.com/user-attachments/assets/78a7d8ca-1cef-4833-9690-41dd32c0bcc8)
I don't know what your issue is, I can use immutables just fine 😕

**Comment by malware-dev** [comment]
![image](https://github.com/user-attachments/assets/d7b9edca-55d8-4121-a0db-d5226f350c3d)

**Comment by malware-dev** [comment]
![image](https://github.com/user-attachments/assets/97508642-54a6-4135-aa42-d20ef076b486)

**Comment by malware-dev** [comment]
I have to ask; are you sure you're using the correct Vector3D from VRageMath?

**Comment by MistaLemur** [comment]
> I have to ask; are you sure you're using the correct Vector3D from VRageMath?
yep

![image](https://github.com/user-attachments/assets/2de5b856-b8aa-4239-b21e-b5b1b4ce2137)

**Comment by MistaLemur** [comment]
Just updated to 2.1.10. Issue appears fixed! 😄
