### ISSUE TITLE
bad minifier

### ISSUE THREAD

**Issue by Aimonxxl** [malforge/mdk2#44]
"I have a problem with the minifier; it doesn't want to work fully."
![изображение](https://github.com/user-attachments/assets/597bc7b1-1c7e-4d6d-b00b-87513de1e83f)

**Comment by Aimonxxl** [comment]
https://github.com/ManuelSchmitz/SCAM - no work full minifier

**Comment by malware-dev** [comment]
What you linked is not an MDK project?

**Comment by malware-dev** [comment]
Please try to find a minimal reproduction. This is just a free-time project for me, I have limited time to work on this.

**Comment by Aimonxxl** [comment]
[SCAM.0.9.153.cs.txt](https://github.com/user-attachments/files/17169256/SCAM.0.9.153.cs.txt)
I can only provide code that compiles in lite mode but refuses to compile in full mode, and I am very weak in programming.

**Comment by malware-dev** [comment]
Thank you. This may be much too large for me to use, but hopefully it can be matched to the other registered bugs and I'll figure it out anyway.

**Comment by malware-dev** [comment]
I was able to find a reproduction. Unfortunately it is a complex problem so is not something I can fix _quickly_.

**Comment by malware-dev** [comment]
Fixed in 2.0.12
