### ISSUE TITLE
Symbol renamer fails when attempting to rename "var"s of structs contained within another class

### ISSUE THREAD

**Issue by InfernoSuperNova** [malforge/mdk2#45]
public class AContainingClass
    {
        
        public struct InlineDirectedStruct
        {
            public double ARandomValue { get; set; }
        }
    }
    
    partial class Program : MyGridProgram
    {

        public List<AContainingClass.InlineDirectedStruct> _inlineDirectedStruct;

        public Program()
        {
            foreach (var structInstance in _inlineDirectedStruct)
            {
                Echo(structInstance.ARandomValue.ToString());
            }
        }
    }
    
    Changing var to AContainingClass.InlineDirectedStruct is an acceptable workaround for the issue.
    
    Tested on 2.0.8

**Comment by malware-dev** [comment]
It's not supposed to modify var at all 😡

**Comment by malware-dev** [comment]
Fixed in 2.0.10
