### ISSUE TITLE
Errors with Mal.Mdk2.PbPackager

### ISSUE THREAD

**Issue by FumbledOrdinance** [malforge/mdk2#47]
I've been chasing my tail trying to get this to work and I can't seem to decipher the instructions. By what I've read this should work.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.12\build\..\tools\mdk.exe" restore "C:\Users\bradd\source\repos\Test Script\Test Script\Test Script.csproj" " exited with code 3.	Test Script	C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.12\build\Mal.Mdk2.PbPackager.props	14

Build Message:
1>------ Rebuild All started: Project: Test Script, Configuration: Debug x64 ------
1>  Found local ini file: C:\Users\bradd\source\repos\Test Script\Test Script\Test Script.mdk.local.ini
1>  Found ini file: C:\Users\bradd\source\repos\Test Script\Test Script\Test Script.mdk.ini
1>  Successfully determined the binary path of Space Engineers: d:\steam\SteamApps\common\SpaceEngineers\Bin64
1>  Loading Space Engineers assemblies from d:\steam\SteamApps\common\SpaceEngineers\Bin64
Restored C:\Users\bradd\source\repos\Test Script\Test Script\Test Script.csproj (in 261 ms).
1>  The system cannot find the path specified.
1>C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.12\build\Mal.Mdk2.PbPackager.props(14,9): error MSB3073: The command ""C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.12\build\..\tools\mdk.exe" restore "C:\Users\bradd\source\repos\Test Script\Test Script\Test Script.csproj" -interactive" exited with code 3.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild completed at 11:13 PM and took 00.458 seconds ==========

**Comment by malware-dev** [comment]
Yep, I broke the latest version, sorry, I am on it

**Comment by malware-dev** [comment]
Fixed (?) in v.2.0.13

**Comment by FumbledOrdinance** [comment]
Just test with v.2.0.13. issues different this time, heres the new messages.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.13\build\..\tools\mdk.exe" pack "C:\Users\bradd\source\repos\Troubleshoot\Troubleshoot\Troubleshoot.csproj"  -configuration Debug -interactive" exited with code -1.	Troubleshoot	C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.13\build\Mal.Mdk2.PbPackager.props	18	

1>------ Rebuild All started: Project: Troubleshoot, Configuration: Debug x64 ------
Restored C:\Users\bradd\source\repos\Troubleshoot\Troubleshoot\Troubleshoot.csproj (in 33 ms).
1>  MDK is restoring ingame script project: Troubleshoot
1>  Troubleshoot -> C:\Users\bradd\source\repos\Troubleshoot\Troubleshoot\bin\Troubleshoot.exe
1>  Compilation failed with errors.
1>  /platform:anycpu32bitpreferred can only be used with /t:exe, /t:winexe and /t:appcontainerexe
1>C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.13\build\Mal.Mdk2.PbPackager.props(18,9): error MSB3073: The command ""C:\Users\bradd\.nuget\packages\mal.mdk2.pbpackager\2.0.13\build\..\tools\mdk.exe" pack "C:\Users\bradd\source\repos\Troubleshoot\Troubleshoot\Troubleshoot.csproj"  -configuration Debug -interactive" exited with code -1.

**Comment by malware-dev** [comment]
I... don't have an answer for that one. It works just fine for me. Could you please zip up your project?
