### ISSUE TITLE
API Listing Update

### ISSUE THREAD

**Issue by wwhitfi7** [malforge/mdk2#51]
The old Mdk-SE wiki is a treasure trove of API information that a lot of external resources point to as an authoritative source on what can be done with the PB in game. Are there any plans to port this information from the old to new repo/project? If so, are there any blockers? If more documentation needs to be generated/manually written I'm happy to contribute some of my time towards accomplishing that, although like everyone involved I tend to be a busy person too 🙂

**Comment by malware-dev** [comment]
No, it's not gonna be ported, eventually I'm gonna make a new disconnected site. In the mean time, this will keep getting updated. I just... have had very little time lately, but I'll get it done.

**Comment by malware-dev** [comment]
There we go, updated.

**Comment by malware-dev** [comment]
Note; the general tutorials have already been ported to the official wiki at https://spaceengineers.wiki.gg/wiki/Scripting. It's only the API listing etc. that won't be because of too many pages.

**Comment by wwhitfi7** [comment]
I'm glad to hear that the API Listing will be surviving as its own disconnected site - and nice to see the tutorials have a home. Let me know if you want help setting up something like a pages site for the API, a lot of the documentation could probably be autogenerated each update from the assemblies themselves I would think. I don't mind working on something like that to share the load 👍

**Comment by malware-dev** [comment]
It's already autogenerated 😊
