### ISSUE TITLE
Cannot build project, code -1

### ISSUE THREAD

**Issue by FcoVega** [malforge/mdk2#53]
Hi, 

I tried to build a new project direct from the template, without any modification and I'm getting the following error message:

Build started at 6:21 PM...
1>------ Build started: Project: Mdk.PbScript1, Configuration: Debug x64 ------
1>Found local ini file: P:\SpaceEngineersScripts\Mdk.PbScript1\Mdk.PbScript1.mdk.local.ini
1>Found ini file: P:\SpaceEngineersScripts\Mdk.PbScript1\Mdk.PbScript1.mdk.ini
1>Successfully determined the binary path of Space Engineers: p:\programs\steam\SteamApps\common\SpaceEngineers\Bin64
1>Loading Space Engineers assemblies from p:\programs\steam\SteamApps\common\SpaceEngineers\Bin64
1>Unable to find a valid MSBuild instance. Please install Visual Studio or the .NET SDK.
1>C:\Users\FcoVe\.nuget\packages\mal.mdk2.pbpackager\2.0.13\build\Mal.Mdk2.PbPackager.props(14,9): error MSB3073: The command ""C:\Users\FcoVe\.nuget\packages\mal.mdk2.pbpackager\2.0.13\build\..\tools\mdk.exe" restore "P:\SpaceEngineersScripts\Mdk.PbScript1\Mdk.PbScript1.csproj" -interactive" exited with code -1.
1>Done building project "Mdk.PbScript1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 6:21 PM and took 03.697 seconds ==========

I checked the installation of visual studio which is v17.12.0, I have checked .NET desktop development workload and .NET framework 4.8, 4.7.2, 4.7.1, 4.7, 4.6.1 SDK and targeting pack

**Comment by FcoVega** [comment]
Doing some research with the error when I updated Visual Studio from v17.5.5 to v17.12.0 it also updated the .NET SDK to version 9.0, following the guide for the VSCode, it says I should have .NET SDK 8.0 which is no longer supported by v17.12.0 of Visual Studio, not sure if this is related or not, but I installed VSCode and .NET 8.0.404 and I can deploy now with MDK2.

**Comment by 4Shage** [comment]
I haved the same issue and resolved it by downloading .NET 8.0 with winget.
Here's command `winget install Microsoft.DotNet.SDK.8`

**Comment by FcoVega** [comment]
Yes, I'm using VSCode for now since I was able to build and deploy with it, I didn't try to install .NET 8 with Visual Studio 17.12 but there is a legend in the Microsoft page that says NET 8.0 is not supported and when I do dotnet --version inside Visual Studio it reports version 9.0, even if I would be able to install version 8.0, I'm assuming I would need to modify something in the code to call the builder 8.0 instead of 9.0, I'm not a software engineer so I'm making a lot of assumptions here. 

I will try to update again Visual Studio to 17.12 and install NET 8.0 and update the results.

**Comment by malware-dev** [comment]
<https://dotnet.microsoft.com/en-us/download/dotnet/8.0>

.NET 9 is days old, I haven't had any time to test against it. But there's indications that you do indeed need .NET 8 specifically, as there's been a few people having issue.

**Comment by malware-dev** [comment]
@FcoVega I am so sorry, I didn't read your entire message... 1. Not supported? I think you might have read that wrong. You can easily download dotnet 8 as of the link above. 2. No, mdk is designed for .NET 8 which is the entire problem. All you need to do is install .NET 8 sdk and you're golden.

I'm so sorry I missed those...

**Comment by FcoVega** [comment]
No worries, I just updated to version 17.12.1 and seems it is working good with .NET 8 installed with the MSI from the page shared.

Thanks!
