### ISSUE TITLE
VRage.Game.ModAPI.Ingame.Utilities not found

### ISSUE THREAD

**Issue by TheMasterofBlubb** [malforge/mdk2#55]
Hi,

I use VS2022 and i installed everything as instructed in the wiki page for Visual Studio.

Now i can compile Projects and see them in my Game. (in general when commenting the problematic using directive)

But using VRage.Game.ModAPI.Ingame.Utilities i can not compile the scripts as VS can not find the Namespace. More specifically i can not use MyIni.

Is there some troubleshooting steps i can do?

**Comment by malware-dev** [comment]
There's no reason why it wouldn't work.

Zip up the project, let me take a look.

**Comment by malware-dev** [comment]
Or, you can reach out on Discord https://discord.gg/keenswh, #programmable-block channel for potential real-time troubleshooting - I'm usually there too.

**Comment by TheMasterofBlubb** [comment]
> There's no reason why it wouldn't work.
> 
> Zip up the project, let me take a look.

Funny enough i get this issue even when using the straight up unedited template. (Then one when you create a new Project in VS)

**Comment by malware-dev** [comment]
Then it is a local issue, I'm afraid

**Comment by malware-dev** [comment]
Hang on; on your secondary test did you make sure to build to x64?

**Comment by TheMasterofBlubb** [comment]
yes, i only have x64 available to select

**Comment by TheMasterofBlubb** [comment]
also Debug anr Release do not make a difference.
Also verified my Gamefiles.

Do you by Chance know how the Assembly Lookup works? Like what folder it checks?

**Comment by malware-dev** [comment]
The assemblies are directly referenced by one of the added by the templates.

**Comment by TheMasterofBlubb** [comment]
Could you check what the assembly name for the MyIni class is? Maybe its just one of my DLLs that is broken

**Comment by TheMasterofBlubb** [comment]
Oh my. Where to begin....

You are correct this in deed was a local issue and a funny one it seems.

I just guessed the Assembly beeing VRage.Game.dll as thats the only fitting one in the whole gamefiles.

Keen was keen enough to include the XMLs with the Classes in the game files so checking if it exists in there was quick (it did not, not even a single line with that namespace). But the XML looked fine otherwise.

So i checked the DLL with dotPeek and there also is no trace of the namespace. 

Now, as i have had my own share of experiences with such issues in another highly moddable game, i deleted the dll and xml and verified my game files AGAIN.

Now it downloaded a NEW DLL, significantly bigger than the old one.

It seems that my DLLs have not been updated since 2018, hence the namespace simply didnt exist at that time....

**Comment by malware-dev** [comment]
... Wow. That's rather incredible. Did you not play ever since? Anyway, I'm glad you were able to resolve the issue.

But yeah. Funny one indeed.

**Comment by TheMasterofBlubb** [comment]
Thats the weirdest part of it all... I am indeed playing RIGHT NOW on a freshly installed (definetly all DLLs from 2024) dedicated server with some friends. Though i had like 1 crash in maybe 5 weeks of playing, which i didnt think was unusual considering some of the mods... But goes to think as to how stable the game is with running .NetFramework 4.6.1 DLLs...


Here the DLL before and after (i think its obvious which one is which)
![grafik](https://github.com/user-attachments/assets/0e7fae43-7cda-41eb-aa72-78de471d085c)

**Comment by malware-dev** [comment]
It doesn't make sense. That's a core DLL. It shouldn't have worked. Are you _sure_ this is the current install direction?

**Comment by TheMasterofBlubb** [comment]
> It doesn't make sense. That's a core DLL. It shouldn't have worked.

i am very sure, i am a software dev (C# at that), and im just as baffled. I checked twice.

And just to make sure checked again and yes its the correct folder. The only explanation i have is that the assemblies have the same version so it wont fail there and as long as you dont call any "bad" methods or classes it should work "fine".

I am just gonna accept that, but now there is a git issue for someone having that issue in the future XD

**Comment by malware-dev** [comment]
I'm also a professional C# software developer. _And_ I am quite familiar with how SE specifically works.

It shouldn't have worked.

**Comment by malware-dev** [comment]
Eeeh you're right though. It is what it is.
