### ISSUE TITLE
Command failing with code -1

### ISSUE THREAD

**Issue by MutterOberin** [malforge/mdk2#56]
I followed the installation process for Visual Studio (Version 17.12.1), created a project and typed in some test script. 

When running the project the build step throws the following error: 

`The command ""C:\Users\****\.nuget\packages\mal.mdk2.pbpackager\2.0.14\build\..\tools\mdk.exe" restore "C:\Users\****\source\repos\SpaceEngineers\TestScript\TestScript.csproj" -interactive" exited with code -1.`

Is there any configuration or something missing?

**Comment by malware-dev** [comment]
You must show the entire error message

**Comment by malware-dev** [comment]
My guess is you don't have .NET 8 SDK installed

**Comment by MutterOberin** [comment]
This is the entire error message :-)

I think my Visual Studio is a bit confused. .NET 8 and 9 are installed but its using 4.8 and I can not select the others.

**Comment by malware-dev** [comment]
It is not the entire error message, you need to look at the full output, not just the error list.

1. Don't mix up ".NET runtime" and ".NET sdk". they're not the same, and I'd guess you have .NET 9 SDK.

2. MDK uses modern .NET. The script projects do not, because Space Engineers does not.

Microsoft keeps making my life difficult with their updates :P

**Comment by MutterOberin** [comment]
Here is the output:

Build started at 13:43...
1>------ Build started: Project: TestScript, Configuration: Release x64 ------
1>Found local ini file: C:\Users\****\source\repos\SpaceEngineers\TestScript\TestScript.mdk.local.ini
1>Found ini file: C:\Users\****\source\repos\SpaceEngineers\TestScript\TestScript.mdk.ini
1>Successfully determined the binary path of Space Engineers: c:\program files (x86)\steam\SteamApps\common\SpaceEngineers\Bin64
1>Loading Space Engineers assemblies from c:\program files (x86)\steam\SteamApps\common\SpaceEngineers\Bin64
1>MDK is restoring ingame script project: TestScript
1>CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point
1>Done building project "TestScript.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 13:43 and took 01.235 seconds ==========

**Comment by MutterOberin** [comment]
I installed the .NET 8 Runtime and the Projects Target Framework is 4.8

The config is Release x64 and I assume it should create an output in the `IngameScripts\local` directory

**Comment by MutterOberin** [comment]
It looks like it works now. I think I accidentally changed it to "Console Application". But the .NET 8 runtime did the trick. 

Thanks a lot for your help! Much appreciated! I might follow up with a pull request for some additional information in the readme file. 

Quick last question: Reselecting the script in SE after code change and distribution can not be prevented, can it?
