### ISSUE TITLE
Remaning program trailing brace when using Mixin

### ISSUE THREAD

**Issue by mflament** [malforge/mdk2#57]
When referencing a class from a Mixin project, the last brace of the Program class is not deleted, leading to in game script compilation error.

**Comment by malware-dev** [comment]
That is interesting, I have three scripts up _right now_ using mixins without any kind of issue, so you will have to elaborate

**Comment by mflament** [comment]
Hello, here is a small an simple project reproducing the issue I have. 
The test case :
* The mixing (Mdk.PbMixin1) simply expose a static method, the ingame script (Mdk.MixinTest) use this method the Main
* No issue when packing the scripts together, MDK² is happy
* But in the generated script.cs, at line 54, there is an extra '}' that seems to be from the Program class.
* All minify options lead to the same error
* If I do not call the Mixin method, no issue, the script.cs is ok
* I use Rider (I love Jetbrains product)
* I have q quick look at your code, `Mdk.CommandLine.IngameScript.Pack.DefaultProcessors.Composer.DeleteTrailingBrace` more exactly, but I am not sure how I could run in Debug, not sure I can help quickly here.

Perhaps I have make a mistake in the way I reference the mixing project in the script project (not using C# often).
And thank you for your cool projects (big fan of the first MDK).

[Mdk.MixinTest.zip](https://github.com/user-attachments/files/17968590/Mdk.MixinTest.zip)
[script.zip](https://github.com/user-attachments/files/17968621/script.zip)

**Comment by malware-dev** [comment]
By the way, there's _supposed_ to be an extra }, it's what exits out of the game's Program class - otherwise extension methods would be impossible. MDK1 does the exact same thing.

**Comment by malware-dev** [comment]
Your output script looks completely correct to me

**Comment by malware-dev** [comment]
Same with the provided project, it works exactly as expected

**Comment by malware-dev** [comment]
I also copy-pasted the script from your script.zip into a PB and it works just fine

**Comment by malware-dev** [comment]
When you paste a script into the programmable block, it is placed inside a code stub that - ignoring namespace imports - looks roughly like this:

```
partial class Program : MyGridProgram
{
	// Your script is placed here
}
```
[Extension methods](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) do not work if they're placed inside of another class. So MDK exits the Program class by adding another } before placing any class that does not reside within the Program class.

This also means that the last } is still added, so the last } in the script needs to be removed in order for the script to become a valid whole.

This is why you find the extra  } at line 54, and why the last } is removed.

**Comment by mflament** [comment]
You are right .... it works perfectly. I don't understand why I had an error and though it was due to this extra }. Sorry for the disturbance, thank you and keep the good work.
I close this ticket.
